from pathlib import Path
p=Path(r'E:\Flow_veo\flowgraph-extension\src\ui\theme.css')
css=r'''

/* Film timeline / assembly */
.timeline-workspace{display:grid;grid-template-rows:auto auto 1fr auto;min-height:0;height:100%;background:#080d14;color:#dce7f5;overflow:hidden}
.timeline-header{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:18px 22px 14px;border-bottom:1px solid #1a2637;background:#0b111a}
.timeline-header h2{margin:3px 0 4px;font-size:20px;letter-spacing:-.02em}.timeline-header p{margin:0;color:#7f90a7;font-size:11px;max-width:760px}
.timeline-summary{display:grid;grid-template-columns:repeat(3,minmax(150px,1fr)) minmax(210px,1.2fr);gap:1px;background:#1a2637;border-bottom:1px solid #1a2637}
.timeline-summary>div,.timeline-summary>label{min-height:58px;background:#0c131d;padding:10px 14px;display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:8px}.timeline-summary svg{color:#748ba8}.timeline-summary span{font-size:9px;color:#7f90a7;text-transform:uppercase;letter-spacing:.08em}.timeline-summary strong{font-size:14px;color:#edf5ff}.timeline-summary label input{width:76px;justify-self:end;background:#090f17;border:1px solid #27374d;color:#e9f3ff;border-radius:5px;padding:5px 7px;font-size:11px}.timeline-summary label em{font-size:9px;color:#6f829a;font-style:normal}
.timeline-editor{display:grid;grid-template-columns:154px minmax(800px,1fr);grid-auto-rows:42px;align-content:start;overflow:auto;background:#080d14}.timeline-ruler-head,.timeline-track-head{position:sticky;left:0;z-index:4;background:#0d151f;border-right:1px solid #223044;border-bottom:1px solid #1a2637;padding:0 12px;display:flex;align-items:center;color:#70849d;font-size:9px;font-weight:800;letter-spacing:.1em}.timeline-ruler{position:relative;min-width:800px;background:#0a111a;border-bottom:1px solid #1a2637}.timeline-ruler span{position:absolute;top:14px;transform:translateX(-1px);font-size:8px;color:#667a94}.timeline-ruler span:before{content:'';position:absolute;left:0;top:-14px;width:1px;height:10px;background:#32445d}
.timeline-track-head{height:42px;justify-content:space-between}.timeline-track-head>div{display:flex;align-items:center;gap:7px;color:#bdcbe0}.timeline-track-head strong{font-size:10px}.timeline-track-head>span{font-size:8px;color:#65778e;letter-spacing:0}.timeline-track-lane{position:relative;min-width:800px;height:42px;background:#091018;border-bottom:1px solid #172335;overflow:hidden}.timeline-track-lane.video{background:#0a111a}.timeline-gridline{position:absolute;top:0;bottom:0;width:1px;background:#172335;pointer-events:none}.timeline-clip{position:absolute;top:5px;height:31px;min-width:36px;border:1px solid #3e6696;background:#183452;border-radius:4px;padding:3px 5px;display:grid;grid-template-columns:auto 1fr auto;gap:5px;align-items:center;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.25)}.timeline-track-lane.dialogue .timeline-clip{border-color:#795e98;background:#332544}.timeline-track-lane.sfx .timeline-clip{border-color:#517a65;background:#203629}.timeline-track-lane.music .timeline-clip{border-color:#8d684c;background:#3d2c20}.timeline-track-lane.subtitle .timeline-clip{border-color:#6c728a;background:#292d3a}.timeline-clip strong{font-size:8px;color:#e9f3ff;white-space:nowrap}.timeline-clip span{font-size:8px;color:#a9bdd7;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.timeline-clip em{font-size:7px;color:#7f9cba;font-style:normal;white-space:nowrap}.timeline-empty-lane{height:100%;display:flex;align-items:center;gap:6px;padding-left:12px;color:#41536a;font-size:9px}
.timeline-footer{min-height:38px;border-top:1px solid #1a2637;background:#0b111a;display:flex;align-items:center;justify-content:space-between;padding:0 16px;color:#687b93;font-size:9px}.timeline-footer strong{color:#b9cce3}
@media(max-width:1100px){.timeline-summary{grid-template-columns:repeat(2,1fr)}.timeline-editor{grid-template-columns:130px minmax(760px,1fr)}}
'''
text=p.read_text(encoding='utf-8')
if '/* Film timeline / assembly */' not in text:
    p.write_text(text+css,encoding='utf-8')
